status = error
name = BigDataTrainingSparkLog4j2

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

rootLogger.level = warn
rootLogger.appenderRef.console.ref = console

logger.repl.name = org.apache.spark.repl
logger.repl.level = error
logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = error
logger.parquet.name = org.apache.parquet
logger.parquet.level = error
logger.hiveMetastore.name = org.apache.hadoop.hive.metastore.RetryingHMSHandler
logger.hiveMetastore.level = fatal
logger.hiveFunctions.name = org.apache.hadoop.hive.ql.exec.FunctionRegistry
logger.hiveFunctions.level = error
