input {
  kafka {
    bootstrap_servers => "kafka:19092"
    topics => ["application.logs"]
    group_id => "logstash-training-logs"
    codec => json
    auto_offset_reset => "earliest"
    add_field => { "[@metadata][target_index]" => "training-logs-%{+YYYY.MM.dd}" }
  }

  kafka {
    bootstrap_servers => "kafka:19092"
    topics => ["sales.raw"]
    group_id => "logstash-training-sales"
    codec => json
    auto_offset_reset => "earliest"
    add_field => { "[@metadata][target_index]" => "training-sales-%{+YYYY.MM.dd}" }
  }

  kafka {
    bootstrap_servers => "kafka:19092"
    topics => ["web.logs.raw"]
    group_id => "logstash-web-logs"
    codec => json
    auto_offset_reset => "earliest"
  }
}

filter {
  if [log_type] == "apache_access" {
    grok {
      match => {
        "message" => '^%{IPORHOST:client_ip} %{DATA:ident} %{DATA:user_id} \[%{HTTPDATE:access_time}\] "%{WORD:method} %{DATA:path} HTTP/%{NUMBER:http_version}" %{INT:status:int} %{INT:bytes_sent:int} "%{DATA:referrer}" "%{DATA:user_agent}" %{INT:response_time_ms:int}$'
      }
      tag_on_failure => ["_web_access_grok_failure"]
    }
    date {
      match => ["access_time", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
    }
    mutate { add_field => { "[@metadata][target_index]" => "web-access-%{+YYYY.MM.dd}" } }
  } else if [log_type] == "application" {
    grok {
      match => {
        "message" => '^%{TIMESTAMP_ISO8601:app_time} %{LOGLEVEL:app_level} service=%{NOTSPACE:app_service} trace_id=%{NOTSPACE:trace_id} message="%{DATA:app_message}"$'
      }
      tag_on_failure => ["_app_grok_failure"]
    }
    date {
      match => ["app_time", "ISO8601"]
      target => "@timestamp"
    }
    mutate { add_field => { "[@metadata][target_index]" => "web-application-%{+YYYY.MM.dd}" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
  stdout { codec => rubydebug }
}
